### ISSUE TITLE
Exported file can't be imported

### ISSUE THREAD

**Issue by paulius90** [angryziber/ipscan#50] opened 2015-10-29 04:22 UTC
In an attempt to workaround favorite problem as file here :

https://github.com/angryziber/ipscan/issues/48

I found exported file from angrip can not be imported correctly.

![errormsg](https://cloud.githubusercontent.com/assets/15161704/10810029/4d3fa674-7e2f-11e5-9eee-d6151acad045.jpg)

**Comment by angryziber** [comment] 2016-01-09 16:49
Can you please provide the file that you are trying to open?

Also, it would be helpful to see the full stack trace of the error.
Please run Angry IP Scanner from the Command Prompt with "java -jar ipscan.exe" and reproduce the error. Stack trace will then be visible in the command window.

**Comment by angryziber** [comment] 2016-01-11 22:07
Most probably this error was due to spaces in some values (Comments?)
In this case, this is now fixed in master.

**Closed** 2016-07-09 21:37 UTC
